/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include"stm32f4xx.h"
#include"stm32fxx_gpio_driver.h"
#include <stdint.h>
#include"delay.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


uint8_t flag = 0;


void EXTI0_IRQHandler(void)
{
	/*STATE A of passenger*/
		GPIO_IRQHandling(GPIO_PIN_NO_0);
		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, SET);
		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_14, SET);
		
		//2.5 mins delay
		delay_sec(150);
		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, RESET);
		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_14, RESET);

}

int main(void)
{
    /* Loop forever */


	//IRQ configurations
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI0, NVIC_IRQ_PRI0);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, SET);

	

	/*initializing the GPIO clock*/
	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&GPIO_LED);
	GPIO_Init(&GPIO_LED1);

    /*LED1 for showing output*/
	GPIO_HANDLE_t GPIO_LED1;
	GPIO_LED1.pGPIOx = GPIOD;
	GPIO_LED1.GPIO_PIN_CONFIG.GPIO_PIN_NUMBER = GPIO_PIN_NO_14;
	GPIO_LED1.GPIO_PIN_CONFIG.GPIO_PIN_MODE   = GPIO_MODE_OUT;
	GPIO_LED1.GPIO_PIN_CONFIG.GPIO_PIN_SPEED  = GPIO_SPEED_HIGH;
	GPIO_LED1.GPIO_PIN_CONFIG.GPIO_PIN_OPTYPE = GPIO_OP_TYPE_PP;
	GPIO_LED1.GPIO_PIN_CONFIG.GPIO_PIN_PUPDR  = GPIO_PU;
	/*BUTTON */
	GPIO_HANDLE_t GPIO_btn;
	GPIO_btn.pGPIOx = GPIOA;
	GPIO_btn.GPIO_PIN_CONFIG.GPIO_PIN_NUMBER = GPIO_PIN_NO_0;
	GPIO_btn.GPIO_PIN_CONFIG.GPIO_PIN_MODE   = GPIO_MODE_IT_FT;
	GPIO_btn.GPIO_PIN_CONFIG.GPIO_PIN_SPEED  = GPIO_SPEED_HIGH;
	GPIO_btn.GPIO_PIN_CONFIG.GPIO_PIN_OPTYPE = GPIO_OP_TYPE_PP;
	GPIO_btn.GPIO_PIN_CONFIG.GPIO_PIN_PUPDR  = GPIO_PU;

	GPIO_PeriClockControl(GPIOA,ENABLE);
	GPIO_Init(&GPIO_btn);

	GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, RESET);
	GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_13, RESET);
	GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_14, RESET);
	GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_15, RESET);
	
	
		/*LED for showing output*/
	GPIO_HANDLE_t GPIO_LED;
	GPIO_LED.pGPIOx = GPIOD;
	GPIO_LED.GPIO_PIN_CONFIG.GPIO_PIN_NUMBER = GPIO_PIN_NO_12;
	GPIO_LED.GPIO_PIN_CONFIG.GPIO_PIN_MODE   = GPIO_MODE_OUT;
	GPIO_LED.GPIO_PIN_CONFIG.GPIO_PIN_SPEED  = GPIO_SPEED_HIGH;
	GPIO_LED.GPIO_PIN_CONFIG.GPIO_PIN_OPTYPE = GPIO_OP_TYPE_PP;
	GPIO_LED.GPIO_PIN_CONFIG.GPIO_PIN_PUPDR  = GPIO_PU;


	
	/*IDLE STATE of passenger*/	
	while(1)
	{
				GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
				GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);
				GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);
				GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);
		
	}
			

}

